Implementando firestore
abnerllobato/barber_app pull request #6
Opened 2022-10-21 23:07 UTC by abnerllobato

Nessa Branch foram iniciadas as configurações do firestore, fazendo com que o usuário seja criado no firebase auth e também seja inserido no banco de dados no caso o firebase_firestore

2022-10-24 13:41 UTC, felipeszu requested changes

2022-10-24 13:41 UTC, felipeszu commented on android/app/build.gradle
> +        minSdkVersion 19
Uhmmmm!!!!! Não sei se isso é uma boa idéia.

2022-10-24 13:41 UTC, felipeszu commented on android/app/src/main/java/Properties.groovy
> +}
Porque temos uma classe vazia? Qual o motivo?

2022-10-24 13:41 UTC, felipeszu commented on lib/models/cadastro_model.dart
> +  String? name;
Cara, aqui falta padronização. temos name com dataCriacao. Dessa forma seu código fica muito inconsistente. 

Tente sempre utilizar nomes em inglês. Como: 
name, createdAt, updatedAt, userType

2022-10-24 13:41 UTC, felipeszu commented on lib/repositories/auth_repository.dart
> +  signup({
Você não precisa de todos esses parametros. Sugiro, passar apenas os necessários, como teremos diferentes tipos de cadastro podemos ter um método para cada cadastro. Como signupCommomUsers({name, email, password})

E dentro do método você trata os outros parametros necessários, como createdAt, updatedAt, userType e o uid

2022-10-24 13:41 UTC, felipeszu commented on lib/repositories/auth_repository.dart
> +        .then((uuid) async {
Tome cuidado ao usar .then() Nesse caso você poderia popular alguma variavel com o resultado de "CreateUserWithEmailAndPassword" e apenas usar da maneira que deseja. Deixa seu código mais limpo e fácil de ler e dar manutenção.

2022-10-24 13:41 UTC, felipeszu commented on lib/repositories/auth_repository.dart
> +  void saveProfileData(
Para que tantos parametros???? qual o motivo de não usarmos o model já criado?

2022-10-24 13:41 UTC, felipeszu commented on lib/views/cadastro/bloc/cadastro_bloc.dart
> +      await _authRepository.signup(
Já comentei sobre a quantidade de parametros acima.

2022-10-24 13:41 UTC, felipeszu commented on lib/views/cadastro/bloc/cadastro_bloc.dart
> +          emit(CadastroFailed(errorMessage: 'Senha Muito Fraca'));
Poxa, senhas fracas podem ser tratadas na ui, usando validators.

2022-10-24 13:41 UTC, felipeszu commented on lib/views/cadastro/bloc/cadastro_bloc.dart
> +          emit(CadastroSuccessState(name: event.name));
Opsss! Temos um sucesso dentro do Catch? Como assim? Me parece bem errado isso.

2022-10-24 13:41 UTC, felipeszu commented on lib/views/cadastro/cadastro_page.dart
>                      return SizedBox(
Um SizedBox com um padding. Seria melhor usar um container

2022-10-24 13:41 UTC, felipeszu commented on lib/views/cadastro/cadastro_page.dart
>              if (state is CadastroSuccessState) {
Uma dica é fazer o login do usuário assim que ele se cadastrar. Deixaria o fluxo mais suave

2022-10-24 15:14 UTC, abnerllobato commented on android/app/build.gradle
> +        minSdkVersion 19
Ok, vou voltar ao original.

2022-10-24 15:16 UTC, abnerllobato commented on android/app/src/main/java/Properties.groovy
> +}
Entrei no Android Studio e como uma das soluções do problema pediu para criar essa classe.

2022-10-24 15:22 UTC, abnerllobato commented on lib/models/cadastro_model.dart
> +  String? name;
Alteradoo !!

2022-10-24 20:11 UTC, felipeszu requested changes

2022-10-24 20:11 UTC, felipeszu commented on lib/views/cadastro/cadastro_page.dart
>        body: BlocProvider<CadastroBloc>(
Trocar no de CadastroBloc -> SignupBloc.
Fazer as mesmas coisas com o event e o state. Não esqueça o nome dos arquivos

2022-10-24 20:11 UTC, felipeszu commented on lib/views/cadastro/bloc/cadastro_bloc.dart
> +    // ignore: invalid_use_of_visible_for_testing_member
🔥

2022-10-24 20:11 UTC, felipeszu commented on lib/services/issues_service.dart
> +    }
usar 
`switch(e){
   case: 'example':
       return 'response';
   default:
        return 'response';
}`

2022-10-24 20:11 UTC, felipeszu commented on lib/repositories/auth_repository.dart
> +  void saveProfileData(UserModel user) async {
`Future<void> saveUserDataOnFirestore`

2022-10-24 20:11 UTC, felipeszu commented on lib/repositories/auth_repository.dart
> +    saveProfileData(user);
await saveProfileData(user)

2022-10-24 20:11 UTC, felipeszu commented on lib/models/cadastro_model.dart
> +import 'package:cloud_firestore/cloud_firestore.dart';
Alterar nome do arquivo

2022-10-25 12:59 UTC, felipeszu requested changes

2022-10-25 12:59 UTC, felipeszu commented on lib/views/signup/bloc/signup_event.dart
> +class LoadCadastroEvent extends SignupEvent {}
LoadCadastroEvent -> LoadSignupEvent

2022-10-25 12:59 UTC, felipeszu commented on lib/views/signup/bloc/signup_event.dart
> +class CadastroButtonEvent extends SignupEvent {
👀

2022-10-28 16:13 UTC, merged